### ISSUE TITLE
[textarea] errorState is not being recalculated when the validators list changes

### ISSUE THREAD

**Issue by gafortuno** [ing-bank/lion#114] opened 2019-06-20 09:41 UTC
Upon adding and removing `.errorValidators = ['required']` dynamically on textarea, when submitting the form without any value on textarea, the form is being submitted. The errorState is false. But, when trying to put something and removing the value before submitting the form, the required validation and working as expected.

**Comment by bashmish** [comment] 2019-06-20 12:49
@gafortuno thanks for your report! We can't reproduce this, can you maybe provide a failing test in a MR?

**Comment by gerjanvangeest** [comment] 2019-09-25 08:11
I'll close this issue, since there is no update since. Please reopen if you have this bug is still there and provide us with more info how to reproduce the bug.

**Closed by gerjanvangeest** 2019-09-25 08:11 UTC
Labels: bug
