### ISSUE TITLE
[dialog] click on a label in a dialog with hidesOnOutsideClick on

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#803] opened 2020-07-07 23:17 UTC
## Describe the bug

When you have a label for an input in a dialog, clicking on the label close the dialog

## To Reproduce

Change the main story of dialog with this (added label, input node and config property on dialog:
```js story
export const main = () => html`
  <style>
    ${demoStyle}
  </style>
  <lion-dialog .config=${{ hidesOnOutsideClick: true }}>
    <button slot="invoker">Click me to open dialog</button>
    <div slot="content" class="dialog">
      <label for="test">test</label>
      <input id="test">
      Hello! You can close this dialog here:
      <button
        class="close-button"
        @click=${e => e.target.dispatchEvent(new Event('close-overlay', { bubbles: true }))}
      >
        ⨯
      </button>
    </div>
  </lion-dialog>
`;
```
2. click on the label

## Expected behavior

Not closing the dialog

**Comment by tlouisse** [comment] 2020-07-13 09:21
Interesting one. The problem is that a click on a label that points to an input, causes the platform to focus the input. Apparently the platform does this via a click on this input.
Two consecutive clicks lead to a mismatch in our code (it makes the 'body handler' misalign with the 'content handler'). Fixed by: https://github.com/ing-bank/lion/pull/815/commits/ece7c0f33e4a4be888bcbc20d90a2b65e261a9c9

**Closed** 2020-07-13 11:48 UTC
