### ISSUE TITLE
Importing Radio and RadioGroup in the wrong order causes runtime exception

### ISSUE THREAD

**Issue by RobM-ADP** [ing-bank/lion#653] opened 2020-03-22 23:38 UTC
## Describe the bug

When importing the radio-group and radio components in the wrong order, a runtime exception is thrown.

## To Reproduce

A simple project to reproduce the error can be found at: https://github.com/RobM-ADP/lion-components-issue

This seems to be an issue with order in which you import the components. I am able to cause the same error using the lion components directly if I import the radio before the radio-group. For example:

No error when using
```
import '@lion/radio-group/lion-radio-group.js';
import '@lion/radio-group/lion-radio.js';
```

But using:
```
import '@lion/radio-group/lion-radio.js';
import '@lion/radio-group/lion-radio-group.js';
```
Results in this error
```
npm.lion.js:2924 Uncaught (in promise) TypeError: Cannot set property 'feedbackData' of undefined
    at Array.<anonymous> (npm.lion.js:2924)
    at AsyncQueue.__run (npm.lion.js:2223)
    at AsyncQueue.add (npm.lion.js:2217)
    at HTMLElement._updateFeedbackComponent (npm.lion.js:2923)
    at HTMLElement.updated (npm.lion.js:2970)
    at HTMLElement.updated (npm.lion.js:4162)
    at HTMLElement.updated (npm.lion.js:7372)
    at HTMLElement.performUpdate (npm.lit-element.js:588)
    at HTMLElement._enqueueUpdate (npm.lit-element.js:528)
    at async HTMLElement._enqueueUpdate (npm.lit-element.js:522)
```

## Expected behavior

I would expect to be able to extend the Radio and RadioGroup in any order or have it at least be documented that the order is significant.

## Additional context

As you can see from the repo above, I am building with webpack and using Typescript so perhaps it is related to my configuration... or I'm just doing something dumb.

**Comment by jorenbroekema** [comment] 2020-04-07 10:05
I will close this now since it should be fixed. At least, on unpkg we no longer have errors anymore, so I believe whatever build setup you have should now also work. Let me know if it's still broken on latest master though, then I will reopen

**Comment by RobM-ADP** [comment] 2020-04-07 13:06
@jorenbroekema if I upgrade to the latest (or pull down master and then link) in the repo mentioned above, I still see the same issue thrown from the `ValidateMixin`
```
ValidateMixin.js:574 Uncaught (in promise) TypeError: Cannot set property 'feedbackData' of undefined
    at Array.eval (ValidateMixin.js:574)
    at AsyncQueue.__run (AsyncQueue.js:28)
    at AsyncQueue.add (AsyncQueue.js:22)
    at HTMLElement._updateFeedbackComponent (ValidateMixin.js:573)
    at HTMLElement.updated (ValidateMixin.js:620)
    at HTMLElement.updated (FormControlMixin.js:129)
    at HTMLElement.updated (FormGroupMixin.js:157)
    at HTMLElement.performUpdate (updating-element.js:574)
    at HTMLElement._enqueueUpdate (updating-element.js:514)
    at async HTMLElement._enqueueUpdate (updating-element.js:508)
```

I would bet that there are a lot more people using webpack that unpkg for building production apps so I think this is still a potentially serious issue. If there is a true order dependency on the imports, then it should at least be documented somewhere.

The repro example has been updated to the latest: https://github.com/RobM-ADP/lion-components-issue

**Comment by jorenbroekema** [comment] 2020-04-07 13:10
There is no true order dependency on the impors that I know of. I will need to look into the reproduction to see what is causing this issue. Thanks for updating it to the latest ;)

**Comment by jorenbroekema** [comment] 2020-07-27 09:39
This is also related to the property binding of choiceValue, see https://github.com/ing-bank/lion/issues/654

**Closed by jorenbroekema** 2020-07-27 09:39 UTC
Labels: bug
