### ISSUE TITLE
[fieldset] Disabling a fieldset does not disable native button

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#170] opened 2019-07-15 20:24 UTC
Not sure if this is intended/unsupported.

When using `lion-fieldset` and setting a `disabled` on it. All lion-elements get disabled. A native button inside the fieldset might look disabled visually, but doesn't seem to be functionally. This can be seen in the fieldset demo's.

**Comment by bashmish** [comment] 2019-07-16 10:17
![image](https://user-images.githubusercontent.com/137844/61286473-36b7fe80-a7c3-11e9-8321-97e1478bcdf4.png)

I checked what I think you described and could not reproduce it. It looks like disabled and you can't click on it. Can you give the code to reproduce it?

My code is:

```js
html`
  <lion-fieldset name="nameGroup" label="Name" disabled>
    <lion-input name="FirstName" label="First Name"></lion-input>
    <lion-input name="LastName" label="Last Name"></lion-input>
    <button @click="${() => alert('Inside click')}">Inside</button>
  </lion-fieldset>
  <button @click="${() => alert('Outside click')}">Outside</button>
`
```

**Comment by bashmish** [comment] 2019-07-16 12:02
After a chat with @erikkroes we found out that mouse clicks are disabled, but with a keyboard you can still focus the button and space/enter to trigger click.

This is definitely a bug because in the platform the native `<fieldset>` does disable a button inside of it.

```html
<form>
  <fieldset disabled>
    <input type="text" value="Value" />
    <button>Button</button>
  </fieldset>
</form>
```

![image](https://user-images.githubusercontent.com/137844/61292749-50147700-a7d2-11e9-815e-682c8a41f365.png)

**Comment by bashmish** [comment] 2019-07-16 12:05
I also think we should make sure `<lion-button>` gets disabled in this context both visually and functionally as a native one, now it is also not working as expected.

**Comment by gerjanvangeest** [comment] 2020-01-29 13:25
Closing this issue for now as a `won't fix`

**Closed by gerjanvangeest** 2020-01-29 13:25 UTC
Labels: bug
