### ISSUE TITLE
[input-datepicker] Sequence doesn't trigger validation message

### ISSUE THREAD

**Issue by mihaisavezi** [ing-bank/lion#273] opened 2019-09-12 10:17 UTC
## Context

I have a custom validator to not be able to select dates earlier than today. I get my data from the backend. The backend gives me a null value. The model value for the input-datepicker field is null. I open the calendar and select a date in the past. The validation returns false.

## Expected

The validation message defined should show.

## Current behaviour

The validation message does not show.

Example repo: https://codesandbox.io/s/bug-lion-web-datepicker-bmv0k

**Comment by jorenbroekema** [comment] 2019-09-17 15:30
Hmmm, for validators to work, the modelValue needs to be valid. In case of datepicker, it needs to be a Date object, otherwise it won't be able to run validation on it. So that's why .modelValue=${null}

For example in your codesandbox, I can set the modelValue to: `.modelValue=${new Date('December 17, 1995 03:24:00')}` and that works fine, it shows the validation message.

But, this works because the modelValue is set in the template, so it's already there before connectedCallback. To clarify, validation messages are shown if:
- The field was prefilled (e.g. modelValue was already there before connectedCallback of the field)
- On-blur of the field
- On-submit of the form that the field is inside of

2 solutions for triggering validation messages after you get your stuff from the backend:
- Run form.resetInteractionStates (but you can also call that on a fieldset, or a specific field, if you just want to reset specifically the thing you are prefilling from the backend)
- Do the first render only AFTER you get the data from the backend, but I wouldn't say this is a great solution.

Maybe in the future we could have something for prepopulation, which can be after first render, ensuring that whatever it is that is prepopulated, to set prefilled to true, which then will render the validation message when it is invalid.

References:
https://github.com/ing-bank/lion/blob/master/packages/validate/docs/ValidationSystem.md#when-validation-feedback-will-be-shown which points to https://github.com/ing-bank/lion/blob/master/packages/field/docs/InteractionStates.md  and has some information on how this works under the hood.

Today we also merged some form system fundamentals demos in storybook, so they may also be insightful for this. It's a first iteration so feedback & contribution is welcome!


please let me know if the issue is solved ;)!

**Comment by gerjanvangeest** [comment] 2019-10-11 10:27
Since there is no response anymore, I'll close this issue.

Please reopen if the explanation above didn't solve your issue.

**Closed by gerjanvangeest** 2019-10-11 10:27 UTC

**Comment by mihaisavezi** [comment] 2019-10-11 13:58
@jorenbroekema - We've managed to find a workaround for our case, but I still have questions. I'd like to say that I understood why it doesn't work in the case I presented, but I don't.

I understood that because the modelValue is 'null' it's not a valid modelValue for the datepicker. That i understant. But after, I as a user, this is what I expect(tell me if I am unreasonable, or if I didn't understand something):

1. select a date ( I assume that the modelValue gets changed to that date)
2. Now the modelValue is valid so I assume validation would run, and if the validation doesn't pass I expect an error message to be shown.

I understand it's triggered on blur. I tried it in the example I provided, and you are right it triggers on blur. But I still believe what I presented is a valid situation and a reasonable expectation a user would have (given the two examples in my sandbox, as a user seeing only the UI you expect the same result) , and a situation you wouldn't expect as a developer using the component. I understand there might be some technical limitations.

If you can give me some pointers, I can have a look see if It's easily fixable.

**Comment by gerjanvangeest** [comment] 2019-10-11 15:03
We sync our validators we put on the input field with the datepicker, to make the unvalid dates disabled, so in all our examples it is not possible to have the use case you described above, which also a better user experience.

So i see two options:

1. Make use of the 4 validators we have:
    - minDateValidator 
    - maxDateValidator
    - minMaxDateValidator
    - isDateDisabledValidator, which allows functions as its parameter.
2. Make it possible to add other validators to [`__syncDisabledDates()`](https://github.com/ing-bank/lion/blob/master/packages/input-datepicker/src/LionInputDatepicker.js#L314)

If you choose for option 2 or disagree with the provided options, please reopen this issue. And we can continue the discussion and find a good solution.
