### ISSUE TITLE
[Safari] Tab key does not work to navigate between input fields

### ISSUE THREAD

**Issue by ovgu12** [ing-bank/lion#1429] opened 2021-06-18 14:39 UTC
## Expected behavior

Use tab key to navigate between input fields works again

## Actual Behavior

When you change some input field for example  "First Name" under

https://lion-web.netlify.app/components/inputs/form/overview/

and then use tab key to move to "Last Name", it does not work. You need to press the tab key again.

**Comment by gerjanvangeest** [comment] 2021-06-22 11:18
This is a duplicate of: https://github.com/ing-bank/lion/issues/1415

**Closed by gerjanvangeest** 2021-06-22 11:18 UTC
