### ISSUE TITLE
[select] select not being registered to lion-form

### ISSUE THREAD

**Issue by jdvivar** [ing-bank/lion#788] opened 2020-06-28 18:57 UTC
## Describe the bug

When obtaining the serialized object of the form, the value from the select form control is not taken into account

## To Reproduce
I've made a very simple lion form to reproduce, with a lion-input and a lion-select. When submitting, the serialized form is console output with the lion-input info only:
https://glitch.com/~simple-lion-form

## Expected behaviour

Both form controls should be part of the serialized output

## Screenshots

<img width="1399" alt="Screenshot 2020-06-28 at 20 54 49" src="https://user-images.githubusercontent.com/690017/85955814-aba72880-b981-11ea-8d6c-4d8779974ce4.png">

## Additional context

The demo is using all latest versions of each of the components used, via snowpack

**Comment by jdvivar** [comment] 2020-06-29 17:22
My approach, for now, is manually adding the form element, which I have implemented in the example:
```form.addFormElement(form.querySelector('#color'))```

Why is that though?

**Comment by tlouisse** [comment] 2020-07-02 08:40
@jdvivar thanks for the bug report 💪 
The problem indeed seems to be that the lion-select is not registered at all (so the form won't attempt to show its serializedValue).

In our integration tests this seems to work: https://github.com/ing-bank/lion/blob/master/packages/form-integrations/test/form-integrations.test.js
We need to dive deeper into this to find out the issue.

**Comment by tlouisse** [comment] 2020-07-06 05:50
Update: when testing the exact same code inside a storybook story, everything works fine.

I suspect it doesn't work because something goes wrong in our registration system, which is pretty complicated because of a ShadyDom bug.
We are planning on simplifying this registration system, so that registration events will be sent on connectedCallback. 

Inside the Glitch demo I added a few lines to see in which order elements are 'bootstrapped' by adding this line:
```js
LitElement.prototype.connectedCallback = function () {
  console.log('cc', this);
  this.enableUpdating();
};
```
I got the following order: simple-form, lion-form, lion-input, lion-select...
So this seems to solve the issue once our registration system is simplified...

**Comment by daKmoR** [comment] 2020-08-04 10:23
I could not reproduce it in the latest version - potentially it got fixed in the sync registration update?

here is the code copied into codepen with 2 adjustments
1. import from `form-core` instead of `validate`
2. commented out `form.addFormElement(form.querySelector('#color'))` as I am not sure what it should do? if you have a specific use case for that please let us know.

https://codepen.io/daKmoR/pen/BaKBbWw

Going to close - if there is something more - feel free to reopen or creating a new issue 🤗

**Closed by daKmoR** 2020-08-04 10:23 UTC
Labels: bug
