### ISSUE TITLE
[input-date] Safari incorrectly reformats dates

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#167] opened 2019-07-15 20:11 UTC
Use Safari and enter a date like 12/12/1212. Tab out of the field. The information in the field becomes 11/12/1212, instead of staying 12/12/1212. 

I could only reproduce this with dates in the past. The edge of this case seems to be in 1939/1940. 12/12/1939 turns into 11/12/1939 when tabbing out. 12/12/1940 does not change.

**Comment by jorenbroekema** [comment] 2020-02-27 12:36
Confirmed the bug for Intl DateTimeFormat in Safari 13.0.5 for MacOS Mojave 10.14.6.

Definitely an external bug, we may want to file it somewhere..

**Comment by jorenbroekema** [comment] 2020-02-27 12:46
https://bugs.webkit.org/show_bug.cgi?id=161623  I debugged some more and reported it here, seems related to this existing bug

**Comment by gerjanvangeest** [comment] 2020-03-04 10:10
Not that spooky here is the history: https://en.wikipedia.org/wiki/Daylight_saving_time#History

**Comment by jorenbroekema** [comment] 2020-03-04 10:36
Turns out it goes wrong already at the Date parsing process:

> new Date('1939-12-06')
< Wed Dec 06 1939 01:00:00 GMT+0100 (CET)

> new Date('12/06/1939')
< Wed Dec 06 1939 00:00:00 GMT+0100 (CET)

**Comment by jorenbroekema** [comment] 2020-03-04 10:48
So there is some issue with the slashes perhaps.., what we do in lion is we get the year-month-day format from the locale, then slice the date-string, then converting it to xx/xx/xxxx format that we know Date object will accept.

What we could try is converting it to ISO String instead. Let's say we get '12-06-1993'
1) split into parts 12 06 1993
2) Check the locale for what the format should be (day-month-year, month-day-year or year-month-day), let's say it is day-month-year for this locale
3) Convert it to ISO String with the knowledge of the day month year format (1993-06-12T00:00:00.000Z
4) Put this ISO String into new Date().

I checked in Safari and it parses the ISO String correctly even for the problematic years, because we hard-set the time and timezone. This should fix all our Date parsing problems that have to do with hours/minutes/etc.

**Comment by maartenst** [comment] 2020-03-05 12:40
Note that this also occurring on Microsoft Edge =< 18 (classic, old, whatever). 
Background reading on why the '/' thing is breaking it here: https://medium.com/@drevets/exploring-unexpected-behavior-with-javascript-date-objects-edaec2b527f9

**Comment by gerjanvangeest** [comment] 2020-11-02 10:38
This is fixed in: https://github.com/ing-bank/lion/pull/1021 :)

**Closed by gerjanvangeest** 2020-11-02 10:38 UTC
Labels: bug, external
