### ISSUE TITLE
Reselecting radio not working. Takes two clicks to reselect radio.

### ISSUE THREAD

**Issue by RobM-ADP** [ing-bank/lion#654] opened 2020-03-23 13:31 UTC
## Describe the bug

When using the radio and radio group components, selecting the radio buttons works initially, but upon reselecting a previously selected radio, it stops registering the first click on the radio and you have to click it twice to reselect

## To Reproduce

In main.ts (same issue happens without typescript though)
```
import '@lion/radio-group/lion-radio-group.js';
import '@lion/radio-group/lion-radio.js';
```
The attempt to use them like so (copied from demo):
```
 <lion-radio-group name="dinos2" label="What are your favourite dinosaurs?">
    <lion-radio label="allosaurus" .choiceValue=${'allosaurus'}></lion-radio>
    <lion-radio label="brontosaurus" .choiceValue=${'brontosaurus'}></lion-radio>
    <lion-radio label="diplodocus" .choiceValue=${'diplodocus'}></lion-radio>
</lion-radio-group>
```

See this repo for an example of the problem: https://github.com/RobM-ADP/lion-components-issue2

## Expected behavior

Radios should be reselectable

## Additional context

This project is being built with webpack and typescript

**Comment by jorenbroekema** [comment] 2020-03-31 15:38
Should be fixed by this PR https://github.com/ing-bank/lion/pull/655, please reopen if the issue persists :)

**Comment by jorenbroekema** [comment] 2020-03-31 15:44
Actually I still get the error on unpkg. @RobM-ADP  could you verify whether the issue is still there?

**Comment by RobM-ADP** [comment] 2020-03-31 17:32
If I take my repo (linked above) and upgrade to the latest via `yarn upgrade --scope @lion --latest` I still see the issue with the radios not being re-selectable. Here are the changes from the upgrade:

```
-    "@lion/button": "^0.5.9",
-    "@lion/input": "^0.5.19",
-    "@lion/radio-group": "^0.8.5",
-    "@lion/switch": "^0.7.2",
+    "@lion/button": "0.5.10",
+    "@lion/input": "0.5.20",
+    "@lion/radio-group": "0.8.6",
+    "@lion/switch": "0.8.0",
```

**Comment by jorenbroekema** [comment] 2020-03-31 18:36
Alright thanks. Seems like dynamic imports in general are a problem for unpkg and perhaps also the build tool you are using to analyze and resolve those dynamic imports in order to bundle your code. Can you perhaps share what you are using, e.g. webpack/rollup/parcel etc. etc.? I might be able to assist you in at least fixing it on your end by adding some configuration to allow for these dynamic imports.

**Comment by RobM-ADP** [comment] 2020-03-31 20:10
I think I figured out what the issue with the re-selection was. In my original test, I had copied the code from the lion demo which is `lit` specific in that the attribute is preceded with a `.`. As a result, I think the `choiceValue` was not being set at all which led to the weird behavior.

That said the behavior when setting the choiceValue via an attribute is not as I would have expected in a non-lit application. For example, this works:
```
 <lion-radio-group name="dinos2" label="What are your favourite dinosaurs?">
    <lion-radio label="allosaurus" choiceValue='"allosaurus"'></lion-radio>
    <lion-radio label="brontosaurus" choiceValue='"brontosaurus"'></lion-radio>
    <lion-radio label="diplodocus" choiceValue='"diplodocus"'></lion-radio>
  </lion-radio-group>
```
while this doesn't
```
 <lion-radio-group name="dinos2" label="What are your favourite dinosaurs?">
    <lion-radio label="allosaurus" choiceValue="allosaurus"></lion-radio>
    <lion-radio label="brontosaurus" choiceValue="brontosaurus"></lion-radio>
    <lion-radio label="diplodocus" choiceValue="diplodocus"></lion-radio>
  </lion-radio-group>
```
The difference is in the double quoting of the `choiceValue` attribute. It seems that it is defined as the type `Object` which forces it to be parsed as a JSON string. So in order to set the radio's value via a string, you need to use double quotes nested inside single quotes as the value of the attribute.

**Comment by jorenbroekema** [comment] 2020-04-01 09:20
Ah I see, yeah the choiceValue property is not reflected as choiceValue attribute, and that it works with '' is more a side-effect/coincidence than something we intend. The reason we opt for a lit property for choiceValue is because we want to support complex values, whereas attributes only support Strings. 

Basically, lion uses lit, so if you use lion, you should probably use lit :\.. I'm assuming you want to use lion in just plain html, for that I would suggest creating simply a `div id="app"` or something in your body as the app container, and just use lit-html to render to this container. 

Hopefully this advice helps, I don't fully know your use case though so I'm making some assumptions :P

**Comment by RobM-ADP** [comment] 2020-04-01 12:40
Thanks @jorenbroekema I know that using lit would make everything "just work". The challenge is that the whole reason we are moving to webcomponents is so that we can build a component library for our design system usable across all the different technologies we use and may use in the future. So we can't dictate that everyone use `lit`. 

Lion sounded like a perfect fit for that but perhaps it has a more limited use that we expected.... or perhaps we just need to customize it more than we had hoped :-(.

**Comment by jorenbroekema** [comment] 2020-04-01 17:01
Well, users can use their own rendering engine, but this technology needs some kind of way at the very least to pass JavaScript properties to the components. A bonus would be an easy way to pass event listeners, but you could set those up any way you want to. So you don't have to use lit, but for some components there are requirements about passing data that requires you to interact with the element with JavaScript.

As an example the .choiceValue or .modelValue property. You can pass it directly in a lit template with the property binding, arguably the easiest method, but you can also render the element anywhere you want, and then imperatively at any point in time (but probably before the users starts trying to interact with it, so best would be after first paint or on connected callback) set the property with JavaScript (`myEl.choiceValue = ...`). Our components should be set up in a way where you can set a property after firstUpdated, and the component it should still update accordingly.

You're in control of this basically, but if you don't use lit you may need to do some additional stuff at least for passing properties to the element and setting events, which you could normally do right inside your template with lit. So yeah, some JS is required at some point, just using it in plain HTML doesn't work for all of lion's components sadly, because of how limited HTML is (attributes only accept strings, no complex values).

Maybe you can share a bit of where you want lion to work, which technologies for example, and I'd be happy to see if I can help to see if we can make it easier to make lion work with those technologies.

**Closed** 2020-07-27 09:37 UTC
Labels: question
