### ISSUE TITLE
[button] tabindex doesn't change when disabled

### ISSUE THREAD

**Issue by mtthp** [ing-bank/lion#308] opened 2019-10-07 18:11 UTC
When setting at initialization the `tabindex` attribute of a `lion-button`, it stays the same even when the component is being `disabled`. Thus, if the button is disabled at first render, it is always at -1.

Here is a little demo of the current behavior : https://stackblitz.com/edit/lion-button-tabindex-disabled?file=index.ts

**Comment by erikkroes** [comment] 2019-10-08 07:10
What would be the use case of manually setting a negative tabindex, instead of setting it to disabled?

**Comment by mtthp** [comment] 2019-10-08 08:52
I didn't write the code where it is set at -1 but from my point of view, it is for accessibilty: if the button is disabled, then you cannot focus it using the tab key and then press space to click on it.

Anyway, the problem here is that the value is automatically set to -1 by the component when it is disabled at the first render and it doesn't change whatever its state is.

**Comment by jorenbroekema** [comment] 2019-10-23 08:21
I was able to reproduce this bug in lit-element
https://stackblitz.com/edit/lit-element-foo

Looks like it works just fine if you make the click handler set the disabled prop directly, but it does not work if you make the click handler toggle a boolean that re-renders the template with `?disabled` prop. I'm gonna let my team look at it as well, then probably file an issue on LitElement

**Comment by SwyserDev** [comment] 2019-10-31 10:38
@jorenbroekema thanks for the feedback! Do you perhaps have an update for us on this issue? Perhaps a link to the issue in LitElement repo?

**Comment by erikkroes** [comment] 2019-11-13 07:27
I've been diving into it a bit but it seems to be a lit-element issue. So I've created one with them: https://github.com/Polymer/lit-element/issues/851

**Comment by tlouisse** [comment] 2019-12-16 10:29
Update for this issue: https://github.com/Polymer/lit-element/issues/851#issuecomment-565999959
It seems to be solvable 👍Let's hope they agree with our use case :)

**Comment by jorenbroekema** [comment] 2020-02-26 10:19
Sorvell proposed the following way to reflect e.g. disabled boolean toggler with another prop like tabindex, using the update() method as a hook https://stackblitz.com/edit/lit-element-foo-rxxnkw 

They were not really persuaded by us to create a public syncUpdate method, according to them we should hook into update() instead before calling super.update(), to create this behavior.

I will close this issue now since it seems to be fixed with this approach, if this is still broken / not working in your use case, feel free to open a new issue :).

**Closed by jorenbroekema** 2020-02-26 10:19 UTC
Labels: bug, external
