### ISSUE TITLE
[storybook demos] Background bleeds through combobox

### ISSUE THREAD

**Issue by erikkroes** [ing-bank/lion#950] opened 2020-09-28 07:59 UTC
## Expected behavior

The listbox that opens stands out clearly. It is on top of all content that was previously there.

## Actual Behavior

<img width="1026" alt="" src="https://user-images.githubusercontent.com/10405024/94405649-26decd00-0171-11eb-903e-4669c1b18488.png">

The next combobox bleeds through the listbox. This makes options unreadable.

**Comment by tlouisse** [comment] 2020-09-28 12:55
This is a z-index isssue that is caused by the demo page of storybook. (even if you give the overlay a high z-index, the competing parent siblings will win.)

There are two ways to fix:
- change the css of storybook. We already do some overrides, but apparently we need more: https://github.com/ing-bank/lion/blob/master/.storybook/preview-head.html
- expose an option in popper that displays the local overlay in the body. Although most likely this will introduce a11y problems, because the input node will be in a different root if our lion-combobox was defined inside shadow dom.

For now I will mark this as a 'demo bug'

**Comment by tlouisse** [comment] 2020-09-28 15:46
I assumed it would be a z-index thing, because of the fact it does overlap the box shadow in the screenshot and not the text. But this is solved by setting a default white background (seems like a sensible default) 🙂

**Closed by tlouisse** 2020-09-28 15:46 UTC
Labels: demos
