### ISSUE TITLE
[select] modelValue is not being properly set once the initial modelValue property is empty

### ISSUE THREAD

**Issue by gafortuno** [ing-bank/lion#93] opened 2019-06-11 11:00 UTC
Steps to replicate:

1. Use `lion-select`
2. Default `modelValue` is empty (using property) `<lion-select .modelValue="${this.someProperty}">`
3. Once the property in the `modelValue` changes, the display in the `lion-select` element doesn't display the value but when trying to use `$0.modelValue`, there is a value.

Vice versa, when I use `value` instead of `modelValue` like `<lion-select .value="${this.someProperty}">`, the display is updated with the correct value BUT the `modelValue` is empty preventing the form to be submitted.

As a workaround, I used `<lion-select .value="${this.someProperty}" .modelValue="${this.someProperty}">`

**Comment by bashmish** [comment] 2019-06-11 14:25
This is at least partially related to this https://github.com/ing-bank/lion/pull/55

let's wait for that MR to be finished first before investigating this bug.

**Comment by tlouisse** [comment] 2019-06-13 18:05
I tried to reproduce the bug (from empty/undefined to a value), but it seems to work for me: https://stackblitz.com/edit/lion-select-bug?file=select-demo.js
Could you maybe fork the Stackblitz and create a failing test case?

**Comment by tlouisse** [comment] 2019-07-02 18:31
As the stackblitz demo shows, you need to listen for model-value-changed and sync to your local model. We should add a demo for this in the section that explains model Values. Also see: https://github.com/ing-bank/lion/issues/145

**Comment by bashmish** [comment] 2019-07-17 15:09
I confirm that [the StackBlitz demo](https://stackblitz.com/edit/lion-select-bug?file=select-demo.js) works as expected and I don't see this bug happening there. So I'm closing this.

Feel free to reopen if you have steps to reproduce it, ideally like @tlouisse suggested: please make a Stackblitz demo where the problem is clearly visible.

**Closed by bashmish** 2019-07-17 15:09 UTC
Labels: demos
