### ISSUE TITLE
[form-core] Enhance Validator instanceof check error message

### ISSUE THREAD

**Issue by tlouisse** [ing-bank/lion#1079] opened 2020-11-04 15:28 UTC
Currently it throws an error, disallowing to run two versions of the extended component set

**Comment by jorenbroekema** [comment] 2020-11-05 09:49
After discussion, this is intended behavior. You don't want to mix different versions of @form-core in the same form, as there will be other issues that you will encounter that don't throw. It's better that we keep throwing to prevent people from combining different versions of form-core in the same form, and not knowing why their fields are misbehaving with no errors.

**Comment by tlouisse** [comment] 2020-11-09 09:49
😉 Thanks, Joren.
I think there are still questions from consumers we need to address:
- The current error message says `Validators array only accepts class instances of Validator. Type "object" found.` This is only confusing, since the type is actually Validator.
- What's the exact boundary between restricting (throwing an error message) and enabling multiple versions (singleton manager) in one runtime.

**Comment by jorenbroekema** [comment] 2020-11-09 14:01
- We can make the message more descriptive, perhaps conditionally adding a "you may have multiple installations of @lion/form-core" if the passed in Validator is of type object. But generally speaking, it's not up to us or the browser to throw descriptive errors that result from duplicate npm installs. We "can't know" about this issue, we can only infer and guess.
- There is no exact boundary but usually I would say "it's fine". Case by case basis we should mention where it is not fine. In this case, don't mix fields in the same form/fieldset from different @lion/form-core installs, because for many reasons you will run into problems. However, multiple installs of form-core on the same page is not a problem though if you don't mix them in the same form.

**Comment by jorenbroekema** [comment] 2020-12-07 19:39
Closing as an enhancement, since I believe the only outcome will be that we should enhance the error message :).

**Closed by jorenbroekema** 2020-12-07 19:39 UTC
Labels: enhancement, votes needed
