### ISSUE TITLE
lionInputAmount doesn't format when submitting using Enter (when you are not blurring out)

### ISSUE THREAD

**Issue by jonathanKoppelman** [ing-bank/lion#1052] opened 2020-10-26 13:57 UTC
When having a lionInputAmount and a user is submitting by entering "Enter" key the formatting that occur on blur does not happen and this makes unpredictable behaviour when working with the data from the input.

![image](https://user-images.githubusercontent.com/30619852/97181549-b2ad3e80-179b-11eb-8d30-3fe102561b6f.png)
![image](https://user-images.githubusercontent.com/30619852/97181318-6e21a300-179b-11eb-8a5b-b4eb0e1a662f.png)

**Comment by gerjanvangeest** [comment] 2020-10-26 15:21
Hi @jonathanKoppelman, thanks for reporting.

Your example isn't very clear, but here is what goes wrong:

Locale is set to `en-GB` (so the decimal separator is `.`) if you type in `1,22` this gets submitted and formatted to `122,00` (since we thought he placed a thousand separator). This is currently tested: https://github.com/ing-bank/lion/blob/master/packages/input-amount/test/parsers.test.js#L92, I'll have to dive into this why we did it this way.

**Comment by tlouisse** [comment] 2020-11-04 08:22
@jonathanKoppelman I think you mean you want the formatting to be shown on pressing enter/submit, right? 
(so you currently see the top image, but you want this to be the bottom image?)

In that case, we would have to add submitted as a formatting condition. Currently formatting is based on an event (blur),
but we can make this more flexible by checking for a condition. Something like:

```js
formatCondition() {
  return !this.focused || this.submitted;
}
```

For this the FormatMixin should be changed. I think it would be a sensible default for Lion as well.

**Comment by tlouisse** [comment] 2020-11-04 08:23
@gerjanvangeest the example you mentioned is also a bit counterintuitive to me.
Maybe @jorenbroekema and @daKmoR remember the exact reasing behind [this](https://github.com/ing-bank/lion/issues/1052#issuecomment-716619243)?

**Comment by tlouisse** [comment] 2020-11-16 12:11
@jonathanKoppelman 

![formatOnEnter](https://user-images.githubusercontent.com/13814138/99251043-f6c8b780-280c-11eb-9a8f-00e18bf2be93.gif)

Trying to reproduce on lion master, and it works actually already as expected: on enter, it formats the value.
Can you maybe give us a sandboxed example where this would not happen?

**Comment by tlouisse** [comment] 2021-03-18 19:28
@jonathanKoppelman will close this one, since it does not seem to be an issue. Feel free to reopen

**Closed** 2021-03-24 18:55 UTC
Labels: bug, enhancement
