### ISSUE TITLE
Listener 'all-forms-open-for-registration'  is never removed

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#283] opened 2019-09-23 19:55 UTC
Listener 'all-forms-open-for-registration' from FormRegisteringMixin.js line 34 is never removed, causing memory leaks and errors in multiple component registration. In my opinion, it should probably be removed after calling _dispatchRegistration

**Comment by AnthonyKot** [comment] 2019-10-04 13:23
https://github.com/ing-bank/lion/pull/300

**Comment by AnthonyKot** [comment] 2019-10-04 13:24
I tried to fix it and some tests failed. Have no idea how to run tests locally if I would like to debug.

**Comment by jorenbroekema** [comment] 2019-10-25 09:33
The tricky part here I think was ensuring that we only remove the specific event listener with the callback that is bound to the current form element, otherwise we break the event for subsequent elements.

```js
formRegistrarManager.removeEventListener(
  'all-forms-open-for-registration',
);
```
would break it, because it removes the manager's event listener altogether

```js
formRegistrarManager.removeEventListener(
  'all-forms-open-for-registration',
  this._dispatchRegistration.bind(this)
);
```
Works because then it only removes the listener of which the callback is bound to the current form element.

Seemingly easy fix, but it isn't :)

Also @AnthonyKot , thanks for trying to pick this up, sorry for not responding to your question to help you out with this. To run tests locally in our repo, all you need to do is do `yarn install` to install dependencies and then run `yarn test` to run the tests locally. For this we assume you have latest NodeJS installed as well as Yarn (alternative to NPM) for dependencies.

I will create a PR to the fix for this and co-author you for the attempt at fixing this Hacktoberfest bug 🤗

**Comment by jorenbroekema** [comment] 2019-10-25 09:42
@lfusiara  https://github.com/ing-bank/lion/pull/349 fix is here, but since there's no reproduction code, I kind of have to guess that this fixes your issue, I can't verify if it does.

**Closed** 2019-10-25 14:11 UTC
Labels: Hacktoberfest, bug, good first issue
