### ISSUE TITLE
[localize] use a different attribute for language

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#234] opened 2019-08-08 07:19 UTC
Currently we use `lang` on the html tag for determining the language of the localize manager. As we saw with https://github.com/ing-bank/lion/issues/152 this breaks when using some kind of translation tool, as that modifies this attribute.

It's fixed in https://github.com/ing-bank/lion/pull/164 by falling back to a default language when a language can't be found. This is good, but doesn't fix other cases where for example you use the locale to send to an API which returns localized content.

Perhaps instead we should use a different attribute like `data-ing-locale` (or something else). That way we have a constant that doesn't accidentally change. It properly fixes using a translation tool, because `data-ing-locale` will determine the language that's used to render the content while `lang` determines the language the content was translated to.

For backwards compatibility we can keep using `lang` if there is no `data-ing-locale`.

**Comment by tlouisse** [comment] 2019-08-08 09:25
I'm not so much into this topic, but if I'm right:

Let's say I want to make a Dutch site, (for which all translations are available to Localize).
I will set:
- lang attr to `nl-NL` 
- fallback locale to `nl-NL` 

Now our users want to translate this to German. The lang attr is changed by Chrome, but the fallback locale will still be used to fetch Dutch translations (which can be translated to German by Chrome (because it expects Dutch input everywhere).

Would it be a possibility then to use the fallback locale to do the merge request?

Since I wasn't too much involved in the changes described above, I might get them wrong and the above doesn't make sense ;)

**Comment by LarsDenBakker** [comment] 2019-08-08 10:06
You're right that it works that way. 

However let's say your dutch website offers `en-GB` texts and it's visited by a polish person. They set the language to `en-GB`, and they will get `en-GB` texts. If they then use google translate to translate that english text into polish, google translate will change `lang` to `pl` and change the text on the screen. The localize manager now gets an unrecognized language and will fallback to `nl-NL` which breaks this scenari.

Instead the localize manager should keep using `en-GB`, and let google translate handle it.

The essence of the problem is that we use `lang` for two things: what's locale do we use for fetching/rendering content, and what's the locale that's currently displayed on the screen. Often those two are the same, but sometimes it's not.

**Comment by tlouisse** [comment] 2019-08-12 07:18
Ah right, for some reason I thought the fallback was introduced to solve the 'Google translate problem'.

Providing an alternative attr would be a good idea, but I think it would raise accessibility problems (screen reader users need to know which language their content is in).

Maybe it would be better if the LocalizeManager only 'syncs up' (when `localize.locale = lang-LOCALE;` is called) and doesn't 'sync down' : https://github.com/ing-bank/lion/blob/97143caedd59a383b8f9c8850590f9cd97384634/packages/localize/src/LocalizeManager.js#L105

**Comment by LarsDenBakker** [comment] 2019-08-12 07:22
I think apps will need to set both at the start, because if google translate kicked in the localize manager shouldn't change the lang attribute again on a language change.

**Comment by tlouisse** [comment] 2019-08-12 11:49
Yeah, good point :)

@dakmor, @LarsDenBakker, @bashmish @gerjanvangeest @jorenbroekema @erikkroes:
Any input for a good name for this attr?
My suggestion would be`data-localize-lang` (emphasizing the connection with localize and the fact it should have a value similar to the original `lang` attr)

**Comment by erikkroes** [comment] 2019-11-13 09:18
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!

**Comment by LarsDenBakker** [comment] 2020-02-24 08:42
I'm reopening this issue. It's actually a bug, not a feature request.

**Comment by LarsDenBakker** [comment] 2020-02-24 08:59
I've been thinking about this, and I'm doubting what the correct solution is.

Just to recap what the problem is:

Let's say you have an app using the localize system. You components with translations as well as components with fetch content from an API. This API uses the accept-language header, which is set by based on the localize system's current locale.

1. User logs in, he is served the app with language nl-NL
2. Some components load, fetch nl-NLtranslations
3. Some components load, fetch nl-NL content from API
4. Google translate kicks in (this is async, can happen at any time), translates all content on the page and changes lang attribute from nl-NL to fr-FR. 
5. New components load, they try to fetch fr-FR translations
  - If component has fr-FR translations -> fr-FR text is rendered, things work fine
  - If they don't have fr-FR translations, it fetches fallback translations en-GB -> google translate won't translate en-GB, so the user sees a mix of en-GB and fr-FR translations
6. New components load, they try to fetch fr-FR content from API
  - If API has fr-FR content -> fr-FR text is rendered, things work fine
  - If API does not have fr-FR content, it throws an error or returns some default language (ex. en-GB) -> google translate won't translate en-GB, so the user sees a mix of en-GB and fr-FR translations

It feels like the right solution is to not rely on the lang attribute at all, it's meant to explain the language of the visible text on the page but not necessarily what language the text should be rendered in technically.

A solution could be to just keep the locale in JS only, and you just need to call `localizeManager.setLocale('...')` with the locale you want to use. That does open up the door to timing issues, if a component is rendered before the function is called. Also when multiple versions of the localize manager is loaded it can create issues.

Other solutions are placing something on the window, or use a different attribute name as explained above.

**Comment by jorenbroekema** [comment] 2020-04-15 09:11
I'm not sure how we would make our components accessible with the proposed solution.

What if there's no Google Translate at all? And the locale is changed from the localize manager (could be on initial render where it's set from undefined to `en-GB`). It should set the lang attribute for accessibility reasons right? How can we ensure that we don't conflict with Google Translate there?

**Comment by jorenbroekema** [comment] 2020-04-15 09:15
I read somewhere that when Google Translate changes the lang attribute, it also adds a class `translated-ltr`. So we could detect whether your localize is about to conflict with Google Translate, and then don't sync to lang (but do sync to data-localize-lang always, because this is private to us and we still want to know what the original language is that the content is rendered as)

**Comment by tlouisse** [comment] 2020-04-15 17:08
Thanks for the clear explanation @LarsDenBakker

I think point 5b (`If they don't have fr-FR translations, it fetches fallback translations en-GB -> google translate won't translate en-GB, so the user sees a mix of en-GB and fr-FR translations`) is a bit different in practice. 
Regardless of whether we use the default (nl-NL) or fallback (en-GB), Google translate will ignore dynamic dom updates.

If I run this on a local server:
```html
<html lang="en-US">
  <body>
    <p> Some English text </p>
    <p> Een beetje Nederlandse tekst </p>
  </body>
</html>
```
And then I set Google translate to German, I get:
```
Ein englischer Text

Ein bisschen niederländischer Text
```
So Google Translate seems to automatically recognize the language (regardless of what is filled in in lang attr). 
The problem is that our users can't enable Google Translate before all translations are loaded. This will be problematic for lazily loaded pages, still.

**Comment by tlouisse** [comment] 2020-04-15 21:57
When I try this locally, step 5 seems to work fine for both the regular and fallback locale. New content gets translated on the fly and the language is autodetected by Google Translate (regardless of what was set in html `lang` attr).

A simple example:
```html
<html lang="en-US">
 <body>
  <p> Some English text </p>
  <p> Een beetje Nederlandse tekst </p>
 </body>
</html>
```
When set to German, this gets translated to:

```
Ein englischer Text
Ein bisschen niederländischer Text
```
 
**However**
The problem seems to be shadow dom: when there is a _shadow root_, Google translate seems to just not work at all.
If you run this fiddle (https://jsfiddle.net/1oxm4v65/3) locally, it turns out that all content in the body gets translated, all content within the shadow root stays the same (you can't illustrate it in the browser since it runs in an iframe, which is also a blocker for Google Translate).

**Closed** 2020-06-08 12:46 UTC
Labels: bug
