### ISSUE TITLE
[field] form elements are not being registered in Edge

### ISSUE THREAD

**Issue by tmsns** [ing-bank/lion#50] opened 2019-05-20 13:31 UTC
For some weird reason, in Edge (IE is fine) parent form elements don't seem to receive the `form-element-register` event and thus doesn't register its child elements. When using derived fieldsets as   `radio-group` some of the methods and properties don't work as expected.

**Comment by bashmish** [comment] 2019-05-23 16:13
I tested current master and all proposed solutions in [this thread](https://github.com/ing-bank/lion/pull/51) applied to the master branch code and could not find any impact on Edge whatsoever, I mean it worked with the old workaround with rAF and it continues to work with `await this.updateComplete`.

Our tests are far from perfect so I do believe you there might be a bug, but I can't reproduce it without a failing test. Can you please create a failing test with `radio-group ` or any other impacted element to show what exactly goes wrong. Or if creating a test is hard, can you point at the demo in the [storybook](https://lion-web-components.netlify.com/) which you open in Edge and which does not work there, also please with clear STR.

Also please specify which version of Edge are you using? I tested Edge 17 and Edge 18.

**Comment by tmsns** [comment] 2019-05-23 16:34
I can reproduce the issue in the storybook when visiting the radiogroup tests directly in Edge: https://lion-web-components.netlify.com/?path=/story/forms-radio-group--default Be aware, it's quite tricky here. You only will see the issue when you keep on choosing multiple different options. The steps to reproduce are:

1. Click on 'allosaurus' => the matching radio is selected
1. Click on 'brontosaurus' => the matching radio is selected (because the actual input is shown here)
1. Click back on 'allosaurus' => all selections vanish

When inspecting the radio group, you should notice that the property `formElements` is an empty object. (in the console make sure you are on frame iframe.html and type `
document.querySelector('lion-radio-group').formElements` )
![image](https://user-images.githubusercontent.com/17364880/58269871-bc519c00-7d88-11e9-8cd0-da52ee87258d.png)

When using a layer on top of `lion-radio` and skinning the graphic, there might seem a different visual feedback of the bug: When doing the second click, the `state-checked` stays on the first element, but the input is acting correctly.

**Comment by tmsns** [comment] 2019-05-23 16:47
While investigating, I noticed that the registration does work in Edge when the container is rendering after some "amount of time" of the initial page load. Here are some of the scenario's that will counter the issue:

- when using the sidebar to navigate to the default test, the registration works correctly
- when the container component has some promise delaying the render (eg. loading dynamic resources with the `import()` and the `localizeMixin`), the registration works correctly 

I've been trying to create a minimal test using stackblitz: https://stackblitz.com/edit/lion-form-nyejmg?file=index.js But after changing some code, even a simple component doesn't seem to render anymore. :p I'm probably doing something wrong here, but still investigating.

**Comment by tmsns** [comment] 2019-05-23 17:00
I forgot to talk about the Edge version :p It's Edge 17

![image](https://user-images.githubusercontent.com/17364880/58271696-ea38df80-7d8c-11e9-9a90-22381db31ed4.png)

**Comment by tmsns** [comment] 2019-05-24 06:56
It's also happening on 18, I see.

**Comment by bashmish** [comment] 2019-05-24 09:48
I confirm that in our storybook in Edge 17/18 the registration does not work and it causes a side effect that can be reproduced using [the steps from above](https://github.com/ing-bank/lion/issues/50#issuecomment-495292765) and this array (`document.querySelector('lion-form').formElements`) is empty there.

At the same time I created a [stackblitz demo](https://stackblitz.com/edit/js-ft652d) based on yours showing that it works well there, both when a form is rendered directly to the document and when rendered within `<my-app></my-app>`.

![screencast 2019-05-24 11-31-37](https://user-images.githubusercontent.com/137844/58318858-eb175300-7e18-11e9-8ca1-0172d493664a.gif)

This means that this might be related to our storybook setup/transpilation, but not an issue with our implementation of LionForm and LionField or other form related elements like radio buttons in your demo.

As such, it has a low impact on the production usage and I have to switch to other form related bug fixing for now. And since Edge will very soon be replaced with a Chromium based version, I would recommend you not to invest time in fixing the storybook for it atm and I'll close this for now.

Feel free to reopen if you can reproduce this bug on Stackblitz or any other place except our storybook.

**Comment by tmsns** [comment] 2019-05-24 10:11
Unfortunately, stackblitz is loading the form dynamically. (you can see a loading bar loading it) This means this case is falling under: 

> when the container component has some promise delaying the render (eg. loading dynamic resources with the import() and the localizeMixin), the registration works correctly

I'm gonna try to have a regular demo. :-)

**Comment by tmsns** [comment] 2019-05-28 10:08
Here is (finally) a repo demoing the issue: https://github.com/tmsns/lion-edge-form-registration-issue

**Closed** 2019-05-29 09:32 UTC
Labels: bug
