### ISSUE TITLE
[lion-select] default value not selected when dynamically rendering options

### ISSUE THREAD

**Issue by T-Motion** [ing-bank/lion#624] opened 2020-03-03 16:56 UTC
## Describe the bug

When you pass a modelvalue to a lion-select, he will automatically select the value that equals the modelvalue (according to the documentation).
But when you dynamically load the options of this lion-select. He does not automatically select the one that equals the modelvalue.

```js
<lion-form .serializedValue=${this.formValue}>`
  <form>
    <lion-radio-group name="boo">
      ${options.map(({ label, value }) => html'
        <lion-radio
          label="${namespace.msg(label)}"
          .choiceValue=${value}
        ></lion-radio>
      ')}}
    </lion-radio-group>
  </form>
</lion-form>
```
When passing a form value to this component, he will not select an option.

I fixed it like this for now:
```js
function isChecked(choiceValue, modelValue) {
  if (modelValue) {
    return modelValue.radioGroup === choiceValue;
  }
  return false;
}
<lion-form .serializedValue=${this.formValue}>`
  <form>
    <lion-radio-group name="boo">
      ${options.map(({ label, value }) => html'
        <lion-radio
          label="${namespace.msg(label)}"
          .choiceValue=${value}
          ?checked=${isChecked(value, this.answer)}
        ></lion-radio>
      ')}}
    </lion-radio-group>
  </form>
</lion-form>
```

**Comment by jorenbroekema** [comment] 2020-03-09 16:23
This probably has to do with that the serializedValue is set before the options are connected to the DOM and done with registering to the form. I think you should `await registrationComplete` on the form and then after that set the serializedValue. That should work. Could you verify?

And maybe then we should have a demo / some documentation about this, because I can see this be a pretty common issue people will have when pre-populating forms.

**Comment by jorenbroekema** [comment] 2020-03-09 16:24
Another option is making serializedValue setter async and awaiting the registrationComplete by default, not sure if this is something we should do though.

**Comment by jorenbroekema** [comment] 2020-03-11 10:22
Note: we only have a registrationReady that you can await to wait for the fieldset to be ready to receive formElements.. but this is not helpful for solving this issue.

```js
const el = fixture(html`
  <lion-fieldset .modelValue=${{ foo: 'bar'}}>`
    <lion-field name="foo"></lion-field>
  </lion-fieldset>
`;

expect(el.firstElementChild.modelValue).to.equal('bar');
```

I think we should start by checking if this fails. Then see if it makes a difference if we set .serializedValue instead, or if it makes a different if we put the field inside a javascript statement like a `.map` loop.

**Comment by T-Motion** [comment] 2020-03-11 14:02
I think the behavior we want is that if a serialized value is already set on a fieldset and fields are dynamically added, the serializedvalue is passed to them.

Failing unit test available here:
https://github.com/ing-bank/lion/blob/3e57b560d915ca22ac7670a156d31b09c2ade466/packages/fieldset/test/lion-fieldset.test.js#L810-L851

**Comment by T-Motion** [comment] 2020-03-11 15:11
#516 is linked i guess?

**Comment by jorenbroekema** [comment] 2020-03-11 16:07
I don't think #516  is related because it's a addFormElement bug vs here it is a ... problem with delegating down a modelValue from fieldset to field, before the field is connected to the DOM. At least I think thats the problem.

The reason your failing test fails is because `<${tag} .modelValue=${{ firstName: 'foo', lastName: 'bar' }}>` --> .modelValue here in the template is a dynamic part, but it is not updated. So even though a requestUpdate fires for this.fields, it does not update the modelValue of the fieldset (tag) I think. You could verify that by doing this:

```js
it('sets modelvalue on dynamically rendered fieldset', async () => { 
  const dynamicallyRenderedFieldsetTagString = defineCE( 
    class extends LitElement { 
      static get properties() { 
        return { 
          fields: Array, 
        }; 
      } 
  
      constructor() { 
        super(); 
        this.fields = [];
        this.myModelValue = ${{ firstName: 'foo', lastName: 'bar' }}; 
      } 
  
      render() { 
        return html` 
          <${tag} .modelValue=${ this.myModelValue }> 
            ${this.fields.map(fieldname => html` 
              <${childTag} name="${fieldname}"></${childTag}> 
            `)} 
          </${tag}> 
        `; 
      } 
    }, 
  ); 
  
  const dynamicallyRenderedFieldsetTag = unsafeStatic(dynamicallyRenderedFieldsetTagString); 
  const el = await fixture(html` 
    <${dynamicallyRenderedFieldsetTag}></${dynamicallyRenderedFieldsetTag}> 
  `); 
  
  await el.updateComplete; 
  
  el.fields = ['firstName', 'middleName', 'lastName']; 
  el.myModelValue = { firstName: 'foo', middleName: 'woof', lastName: 'bar' };
  await el.updateComplete; 
  const lionFieldSet = el.shadowRoot.querySelector('lion-fieldset'); 
  
  expect(lionFieldSet.firstElementChild.modelValue).to.equal('foo'); 
}); 
```
I think now it should pass if my untested pseudo code isn't doing something awful.

Can you try 
```js
const el = fixture(html`
  <${tag} .modelValue=${{ foo: 'bar'}}>
    <${childTag} name="foo"></${childTag}>
  </${tag}>
`;

expect(el.firstElementChild.modelValue).to.equal('bar');
```
and
```js
const el = fixture(html`
  <${tag} .serializedValue=${{ foo: 'bar'}}>
    <${childTag} name="foo"></${childTag}>
  </${tag}>
`;

expect(el.firstElementChild.serializedValue).to.equal('bar');
```
and 
```js
const el = fixture(html`
  <${tag} .serializedValue=${{ foo: 'hello', bar: 'sup' }}>
    ${['foo', 'bar'].map(name => html`
      <${childTag} name="${name}"></${childTag}>
    `)}
  </${tag}>
`;

expect(el.firstElementChild.serializedValue).to.equal('hello');
expect(el.lastElementChild.serializedValue).to.equal('sup');
```

**Comment by jorenbroekema** [comment] 2020-03-11 16:11
The last test there ^ is from what I can tell the closest isolated test that resembles your reproduction, if it passes, we're gonna have to try to create a PR with a demo that reproduces it and then I can look into it further into getting the most isolated failing test possible, and then we can find the appropriate solution 😅. My suspicion is that the cause is that .serializedValue in the template is evaluated before the field is connected to DOM, so the value is never reflected in the field. If that's the case (a timing issue), I have ideas to resolve it through a mixin we have in lion, but we need to be really sure what the root cause is ^^

**Comment by jorenbroekema** [comment] 2020-03-12 16:00
```js
it.only('sets modelvalue on dynamically rendered fieldset', async () => {
  const dynamicallyRenderedFieldsetTagString = defineCE(
    class extends LitElement {
      static get properties() {
        return {
          fields: Array,
        };
      }

      constructor() {
        super();
        this.fields = ['firstName', 'lastName'];
      }

      render() {
        return html`
          <${tag} .modelValue=${{ firstName: 'foo', lastName: 'bar' }}>
            ${this.fields.map(
              field => html`
              <${childTag} name="${field}"></${childTag}>
            `,
            )}
          </${tag}>
        `;
      }
    },
  );

  const dynamicallyRenderedFieldsetTag = unsafeStatic(dynamicallyRenderedFieldsetTagString);
  const el = await fixture(html`
    <${dynamicallyRenderedFieldsetTag}></${dynamicallyRenderedFieldsetTag}>
  `);
  await el.updateComplete;
  const fieldset = el.shadowRoot.querySelector('lion-fieldset');

  expect(fieldset.formElements[0].modelValue).to.equal('foo');
  expect(fieldset.formElements[1].modelValue).to.equal('bar');

  el.fields = ['firstName', 'lastName', 'middleName'];
  await el.updateComplete;
  fieldset.modelValue = { firstName: 'foo', lastName: 'bar', middleName: 'woof' };

  expect(fieldset.formElements[0].modelValue).to.equal('foo');
  expect(fieldset.formElements[1].modelValue).to.equal('bar');
  expect(fieldset.formElements[2].modelValue).to.equal('woof');
});
```
This test showcases the problem, and it's one that we cannot solve on our end. Essentially, on initial render the fieldset waits for `firstUpdated` before it allows `modelValue`/`serializedValue`/`formattedValue` setters to sync downwards to its nested form elements. 

Here is some debugging for context:
<img width="383" alt="Screenshot 2020-03-12 at 12 34 37" src="https://user-images.githubusercontent.com/36734656/76518007-a5d31900-645e-11ea-9995-dc4d958fe4df.png">

When you re-render the form with a couple of new fields, usually the fieldset is not re-rendered, so that means that the setters will execute before the new fields are connected to the DOM. You will have to await the updateComplete and then re-set the modelValue for you to get the expected outcome. 

We cannot automate this on our end, because even if we make the value setters fire a new promise to await for registrationReady, we can never resolve it because there is no hook for the fieldset to know that it's ready (firstUpdated already happened, and updated won't happen because fieldset is not getting re-rendered/changed himself). Soooo it's a logical problem we cannot solve, we can only solve this by making the entire registration system synchronous again....

Eventually we want to do this, our form registration system as it is now, is almost entirely for polyfilling for IE11. Then I think we can look into this again and see what we can do to support this kind of use case. For now I would suggest using the value setters on a per-field basis, or to await all updates and then set the form/fieldset value explicitly.

Hopefully my long message makes sense, it's a pretty complex issue, I hope the workarounds are acceptable for now (1. awaiting updateComplete and setting the value after that, 2. setting the values on the respective fields instead of the form/fieldset)

**Comment by jorenbroekema** [comment] 2020-03-18 11:39
Reopening this, since we (@tlouisse and I) had an idea: in the `addFormElement` of the fieldset, we can re-evaluate the modelValue/serializedValue. Now that a new element has registered, we could re-invoke the `setValueMapForAllFormElements` to sync down to the children.

**Comment by tlouisse** [comment] 2021-04-19 09:13
@T-Motion will be fixed by https://github.com/ing-bank/lion/pull/1341/commits/b5c0e608bfcefca45dd165569c4d03ee6150aab7
Please let us know if it worked for you :)

**Closed** 2021-04-20 11:49 UTC
Labels: bug
