### ISSUE TITLE
[select-rich] Implement @change event

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#933] opened 2020-09-11 19:09 UTC
There is currently only `@model-value-changed` event on the select-rich component. I would like to have a `@change` event with the same behavior of native select change event.

**Comment by MathieuPuech** [comment] 2020-09-14 18:48
I can create a PR if you agree with that

**Comment by MathieuPuech** [comment] 2020-09-17 14:06
I think we may not use `change` for the event name since it's not a trusted event. What should be the name of this event?

**Comment by jorenbroekema** [comment] 2020-10-08 09:55
Hmm I think in general you should use `@model-value-changed` instead of `@changed`. The reason why you can use `@changed` sometimes is probably because that custom input wraps a native input, which is not the case for a rich select. We could dispatch it ourselves, but I'm not sure what the added value would be over `@model-value-changed`, they would essentially be synonymous if we did this right?

**Comment by jorenbroekema** [comment] 2020-10-08 09:56
I think I'm moving this to discussion since it's not a bug but more a discussion or feature request

**Closed** 2020-10-08 09:56 UTC
