### ISSUE TITLE
resetInteractionState  part of resetGroup doesn't work outside of form

### ISSUE THREAD

**Issue by RickdeGroot** [ing-bank/lion#336] opened 2019-10-18 15:29 UTC
When the resetGroup funtion is called outside the form it clears the fields but doesnt reset the interactionstate(they remain dirty)

'Form Submit/Reset', () => {
    const submit = () => {
      const form = document.querySelector('#form');
      if (form.errorState === false) {
        console.log(form.serializeGroup());
        form.resetGroup();
      }
    };

by just adding  form.resetGroup(); to the Form storybook you can see the behavior,
if you click "Reset" it works fine. When you click "Submit" the fields are cleared as expected but the validations are triggered because the fields are still dirty.

the resetInteractionState call by ResetGroup should remove dirty/state-dirty

**Comment by gerjanvangeest** [comment] 2019-10-21 07:16
The issue is that the `submit` is still in progress while you `reset`, which causes the following:

- serialize
- reset
- submit (with empty values, so giving warnings)

Calling the `reset` in a separate function works.

Is the above example your actual use case, or just a way to demonstrate?

**Comment by palash2601** [comment] 2019-10-21 08:46
@gerjanvangeest We do have a scenario as below:

1. User fills data in form and Submits it
2. Filled data is displayed in a table on same page
3. User gets the empty form again to fill new data

So to have the above flow we need to reset the form on submit

**Comment by gerjanvangeest** [comment] 2019-10-21 09:00
Ok, i labelled it as a bug, so we can pick it up soon. If anybody has a good idea and time please share or make a pull request.

**Comment by RickdeGroot** [comment] 2019-10-31 15:06
Had a quick look, the issue is not the actual state-dirty, it's the state-error-show.

**Comment by palash2601** [comment] 2019-11-01 11:24
[This](https://github.com/ing-bank/lion/issues/336#issuecomment-544382113) input from @gerjanvangeest is correct

So to have `reset` wait for `serialize` and `submit` tasks to be completed `updateComplete` hook of LitElement can be used.

```js
'Form Submit/Reset', () => {
  const submit = async () => {
  const form = document.querySelector('#form');
  if (form.errorState === false) {
    console.log(form.serializeGroup());
    await form.updateComplete;
    form.resetGroup();
  }
};
```

Please try once.

Although it would be good if this is handled internally

**Comment by RickdeGroot** [comment] 2019-11-04 18:37
created pull request https://github.com/ing-bank/lion/pull/369 with the code proposed by @palash2601

**Comment by jorenbroekema** [comment] 2019-11-12 13:07
I need some help understanding Palash's comment.

As I understand:
```js
console.log(form.serializeGroup());
await form.updateComplete;
form.resetGroup(); // --> does not reset interaction state correctly if we omit the updateComplete
```

As far as I know, serializeGroup() is completely synchronous, and it does cause the queueing of updates in LitElement. So I am quite confused why `.updateComplete` would solve this issue.

My hypothesis (the numbers are chronologically in terms of timings):
1) You are inside an input which is dirty = false
2) You put some random string inside the input
3) You press the submit button which fires the event (this is all synchronous)
4) Fieldset/form and its fields are serialized (still synchronous)
5) resetGroup is called (still synchronous)
6) resetGroup calls resetInteractionState which sets dirty to false (still synchronous)
7) By pressing the submit button you left the input field, which result in the field becoming dirty (this is asynchronous, therefore it happens after resetGroup happens).

This hypothesis will need to be confirmed of course, but if I am correct, we should not put `await updateComplete` in the `resetGroup`, but rather inside the resetInteractionState, because interaction states are asynchronous (they are Lit properties), resetGroup is not asynchronous.

From the pull request and my comments there, you can see in the tests that now all of a sudden we need to await nextFrame() or await updateComplete in places where we did not need that before. To me this can be considered a breaking change if people expect resetGroup to be a synchronous action and now all of a sudden, it isn't.

Thoughts?

**Comment by RickdeGroot** [comment] 2019-11-12 14:01
But if you prefer to keep `resetGroup` synchronous we can just make `resetInteractionState` async, it will only require us to use awaits for test that actually test the `resetInteractionState` and not all the `resetGroup` tests

**Comment by palash2601** [comment] 2019-11-13 09:43
> I like the demo provided by Palash, and we should convert that to a failing test to start off with :).
> 
> I don't agree with the fix as proposed by Palash though. I looked into the PR and found some problems, I'll try to explain it as best as I can.
> 
> As far as I know, serializeGroup() is completely synchronous, and it does cause the queueing of updates in LitElement. So I am quite confused why `.updateComplete` would solve the root issue.
> 
> My hypothesis (the numbers are chronologically in terms of timings):
> 
> 1. You are inside an input which is dirty = false
> 2. You put some random string inside the input
> 3. You press the submit button which fires the event (this is all synchronous)
> 4. Fieldset/form and its fields are serialized (still synchronous)
> 5. resetGroup is called (still synchronous)
> 6. resetGroup calls resetInteractionState which sets dirty to false (still synchronous)
> 7. By pressing the submit button you left the input field, which result in the field becoming dirty (this is asynchronous, therefore it happens after resetGroup happens).
> 
> Root problem: Interaction states are reset (to false) before the interaction states were set by the act of leaving the field. That's why your field is still dirty.
> 
> This hypothesis will need to be confirmed of course, but if I am correct, we should not put `await updateComplete` in the `resetGroup`, but rather inside the resetInteractionState, because interaction states are asynchronous (they are Lit properties). resetGroup, as far as I can tell, is not asynchronous.
> 
> From the pull request and my comments there, you can see in the tests that now all of a sudden we need to await nextFrame() or await updateComplete in places where we did not need that before. To me this can be considered a breaking change if people expect resetGroup to be a synchronous action and now all of a sudden, it isn't.
> 
> Thoughts?

@jorenbroekema 

I check the flow again and it seems that complete flow is not synchronous

The `serialize` and `reset` does not wait for `submit` to be completed. I got this hint from the comment from @gerjanvangeest after which I debugged and that was correct.

If you check [here] (https://github.com/ing-bank/lion/blob/master/packages/form/src/LionForm.js#L46), the submit event is fired and in parallel serialize and reset gets called.

So some mechanism is needed to wait for `submit ` process to be complete before `reset` can be called. And `updateComplete`  looked to be only option as of now.

I suggested to have `updateComplete` in reset function, but that would not make sense when only reset is called with submit.

Correct me if I am wrong somewhere :)

**Comment by jorenbroekema** [comment] 2019-11-13 14:44
You mention "parallel" but I assume you mean "synchronously" which would be sequential. Parallel implies multi-threaded which usually only happens when doing asynchronous things right?

I don't think we need to wait for the submit process at all. There's nothing to wait on, because the process is entirely synchronous as far as I can tell.

We need to start from scratch in my opinion by creating a single failing test that shows the issue, and go from there:

```js
it.only('reset group happens after submit group', async () => {
  const el = await fixture(html`
    <lion-form
      @submit=${() => {
        console.log(document.querySelector('lion-form').serializeGroup());
        document.querySelector('lion-form').resetGroup();
      }}
    >
      <form>
        <lion-input name="woof" .modelValue="${'Foo'}"></lion-input>
        <button></button>
      </form>
    </lion-form>
  `);

  const btn = el.querySelector('button');
  const input = el.querySelector('lion-input');
  input.dirty = true;
  input.touched = true;

  expect(input.dirty).to.be.true;
  expect(input.touched).to.be.true;
  btn.click();

  expect(input.dirty).to.be.false;
  expect(input.touched).to.be.false;
});
```

This tests passes for me, so basically I can't reproduce your issue :\

**Comment by jorenbroekema** [comment] 2019-11-13 14:57
I did some more debugging with the Storybook story that you guys pointed out.

I changed the story a little bit to troubleshoot:
```js
const submit = () => {
  const form = document.querySelector('#form');
  console.log(form.serializeGroup());
  form.resetGroup();
};
return html`
<lion-form id="form" @submit="${submit}"
  ><form>
    <lion-fieldset label="Name" name="name">
      <lion-input
        name="firstName"
        label="First Name"
        .errorValidators=${['required', maxLengthValidator(15)]}
      >
      </lion-input>
      <h-output
        .show=${['dirty', 'touched', 'submitted', 'prefilled', 'errorState', 'errorShow']}
      ></h-output>
      <lion-input
        name="lastName"
        label="Last Name"
        .errorValidators=${['required', maxLengthValidator(15)]}
      >
      </lion-input>
      <h-output
        .show=${['dirty', 'touched', 'submitted', 'prefilled', 'errorState', 'errorShow']}
      ></h-output>
    </lion-fieldset>
    <button type="submit">Submit</button>
    <button type="button" @click=${() => document.querySelector('#form').resetGroup()}>
      Reset
    </button>
    <p>
      A reset button should never be offered to users. This button is only used here to
      demonstrate the functionality.
    </p>
  </form></lion-form
>`;
```

Something is going on with the error message for the first input..

<img width="633" alt="Screenshot 2019-11-13 at 15 56 18" src="https://user-images.githubusercontent.com/36734656/68774998-278c7480-062e-11ea-9505-651e7715f9ee.png">

Strangely, it has errorState and errorShow set to true... but it doesn't show me the error message.

Reproduce steps:
1) Type into the first input, then remove it. The field will be touched, dirty, and the feedback message shows!
2) Type into the second input
3) Watch the feedback message of the first input disappear 😱

**Comment by tlouisse** [comment] 2019-12-05 13:48
Hey,

I think the problem is the order of handling submit event listeners (currently, `resetGroup` (called in the **custom** listener will be called before `submitGroup` (handled in the **internal** listener))). 

If I switch these two lines, the problem will be solved 👍  (https://github.com/ing-bank/lion/blob/master/packages/form/src/LionForm.js#L46):
```
this.dispatchEvent(new Event('submit', { bubbles: true }));
this.submitGroup();
```

I will make a fix for this in lion#master, that means it will be available in the next major version of our extension layer.

In the meantime, I would recommend a workaround:

```
// TODO: remove this timeout when migrated to next major version
setTimeout(() => {
  form.resetGroup();
});
```

**Closed** 2019-12-06 09:30 UTC
Labels: bug
