### ISSUE TITLE
[validate] loadDefaultFeedbackMessages fails to load in unpkg

### ISSUE THREAD

**Issue by LarsDenBakker** [ing-bank/lion#396] opened 2019-11-26 07:30 UTC
I'm unable to demo lion using unpkg, because it throws an error when serving https://unpkg.com/@lion/validate@0.4.0/src/loadDefaultFeedbackMessages.js?module

See: https://jsbin.com/vimisivawa/edit?html,output as an example.

**Comment by jorenbroekema** [comment] 2020-03-09 17:32
@LarsDenBakker really late, but do you know what could be causing this? I don't have much experience with unpkg, is this something we need to change on our end?

**Comment by jorenbroekema** [comment] 2020-03-23 15:03
Probably due to

```js
return import(`../../${locale}.js`);
```

being hard to statically analyze. Most build tools don't provide out of the box support for it.

Action on our side could be a prepublish step where we analyze our file system of existing translation files and generate a switch case based on that, that way we avoid the dynamic statement inside the dynamic import. And we also avoid the ugly switch in our source code, it would only be in the published code. 

That should fix unpkg, and other build tools, from error'ing on it.

**Comment by jorenbroekema** [comment] 2020-03-23 15:04
Related issues that are likely caused by this:
https://github.com/ing-bank/lion/issues/654
https://github.com/ing-bank/lion/issues/653

**Comment by jorenbroekema** [comment] 2020-03-31 15:49
Should be fixed by this PR https://github.com/ing-bank/lion/pull/655 but seems like it isn't. https://unpkg.com/@lion/validate@0.9.0/src/loadDefaultFeedbackMessages.js?module

Not sure where to look, quite hard to debug unpkg :P but I can see that the same error is thrown for other files with the switch statement with dynamic imports e.g. @lion/input-iban/src/validators

**Comment by jorenbroekema** [comment] 2020-03-31 15:50
Same for https://unpkg.com/@lion/input-datepicker@0.11.1/src/LionCalendarOverlayFrame.js

**Comment by daKmoR** [comment] 2020-03-31 17:53
I did check out unpkg and it seems to be an issue with dynamic imports that have a ` in it.

like what we have in that file
```js
return import(`../translations/en.js`);
```

I opened an issue on unpkg and added a filing test
https://github.com/mjackson/unpkg/issues/253

I think however replacing the \` with a `'` will be a better solution for our issue... we use it 5 times so it should be a straight forward change

**Comment by daKmoR** [comment] 2020-04-02 16:47
oohhhh yes it finally works 💪

https://unpkg.com/@lion/validate@0.9.1/src/loadDefaultFeedbackMessages.js?module

**Closed by daKmoR** 2020-04-02 16:47 UTC
Labels: bug
