### ISSUE TITLE
lion-form is submitted 2 times

### ISSUE THREAD

**Issue by lfusiara** [ing-bank/lion#322] opened 2019-10-12 21:46 UTC
In code like that, if you push enter on doc field form is submitted 2 times

```
    return html`
      <lion-form id="client-search-form" @submit=${e => console.log(e)}>
        <form>
          <lion-input name="doc"></lion-input>
          <lion-button type="submit" name="sub"></lion-button>
        </form>
      </lion-form>
    `;
```

**Comment by gerjanvangeest** [comment] 2019-10-14 06:03
Hi @lfusiara, we had this bug a few weeks ago too, and fixed it in this pull request: https://github.com/ing-bank/lion/issues/240

Did you use the latest version, or could it be that the issue is already resolved in the latest version of `lion`?

**Comment by SantiEspada** [comment] 2019-10-14 10:34
I think it is actually caused by that pull request, there is another related issue #316

**Comment by gerjanvangeest** [comment] 2019-10-15 12:07
Should be fixed at: https://github.com/ing-bank/lion/pull/328

**Closed** 2019-10-21 07:28 UTC
Labels: bug
